spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/glaceon_inventory}
    #    url: jdbc:postgresql://localhost:5432/crm_test
    username: postgres
    password: 98836
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
  flyway:
    enabled: true
server:
  port: 8082